### ISSUE TITLE
node 6 breaks this

### ISSUE THREAD

**Issue by mcarifio** [allenluce/node-autovivify#1]
First, ty for a useful module.

Next, for node 6:

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

$ node --version
v6.1.0

$ node
> var Av = require('autovivify');
undefined
> var used = new Av();
undefined
> used.x.y =1
1
> used.x
{ y: 1 }
> used
{ x: { y: 1 } }

> Object.prototype.toString.call(used) // no toString() method?, how do I find the actual type of 'used'?
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted

**Comment by allenluce** [comment]
Looks like this is sensitive to a change in v8 between 4.8.271.17 and 4.9.385.18. I was able to confirm that this breaks with node's commit 079973b96 (and works on 893835539). Updating nan/node-gyp didn't magically fix it, so I guess it's going to take a little more digging.

**Comment by allenluce** [comment]
I'm still totally sure what is going on but did add a `toString()` method. In previous versions, v8 compensates for the lack of one on the embedded object but that seems to have broken with the newer versions.

1.0.5 is now up. `Object.prototype.toString()` still bombs when applied to an autovivified object but the `.toString()` method on the object itself no longer does. Let me know if that fits your use.

**Comment by allenluce** [comment]
OK, figured it out. The 1.0.6 version should no longer bomb on `Object.prototype.toString.call()`. Type returns as '[object AutoVivify]'. If there's a call to have it masquerade as a '[object Object]' I can probably build that in.
